### ISSUE TITLE
How to add other  hand rankings?

### ISSUE THREAD

**Issue by fanios** [Rickmey/PokerHandEvaluationTool#1]
Hi,I  want to make a six-plus Hold'em evaluation with your work .But I don't know how to add other hand rankings and how to reduce the basic cards the game plays.May you give some suggestions ?Thank you .

**Comment by Rickmey** [comment]
/src/PokerHandEvaluator/TexasHoldem/TexasHoldemEvaluator.cs line 30
Just switch the numbers to get the ranking you need.

Do you want to use my UI? Do you only need the value of a hand or do you want a simulation (handodds)?

Optimization:
Six-plus Hold'em is played with 36 cards, so we still need a 64bit long. The GetHandValue method cannot be changed because we can still have all hand types. The size of the lookup tables can be reduced but I'm not sure that would increase performance.
The general approach is to change everything that is 13 or a multiple of 13 to 9, because each suit only has 9 cards instead of 13.

**Comment by fanios** [comment]
Thanks a lot .I need the handodds mostly .UI is necessary too. How to deal with the minimum straight(A,6,7,8,9)?Will it be solved with changing all 13 to 9?I think what to do with UI is to disable 2~5card buttons.

**Comment by Rickmey** [comment]
The simplest solution is to disable 2-5 in the UI.  However the lowest straight is problematic, because you need to generate a new straight lookup table. For some reason this generation method does not exist in my code. To write your own method you really need a deep understanding of how the algorithm works. I think if you want to change from 13 to 9 you need that anyway.

In general the lookup tables use hands as index. An empty hand returns index 0.
For the straight table we know that we need a hand with 5-7 cards (bits). We don't need suits and can work with ranks only (currently 13 2-A). The basic idea is to form every 5-7 bit combination and check if those bits are connected. Exception is the low straight - 4 connected + highest rank (A counts as high). If there is no straight the value is 0. If you have a straight the value is the lowest card from the straight 1 shifted to the left. Don't shift A low straights.
For the current 13 ranks system.
hand: 0.0000.0001.1111 (bits) = 31 (number) = 6,5,4,3,2 (ranks)
1 shift left
value: 0.0000.0000.0010 (bits) = 2 (number)

hand: 1.0000.0000.1111 (bits) = 4111 (number) = A,5,4,3,2 (ranks)
unshifted
value: 0.0000.0000.0001 (bits) = 1 (number)

hand: 1.1111.0000.0000 (bits) = 7936 (number) = A,K,Q,J,T (ranks)
1 shift left
value: 0.0010.0000.0000 (bits) = 512 (number)

hand: 0.1111.1000.0000 (bits) = 3968 (number) = K,Q,J,T,9 (ranks)
1 shift left
value: 0.0001.0000.0000 (bits) = 256 (number)

**Comment by fanios** [comment]
Thank you for your detailed answers .I get you.
